import React, { useState, useEffect, useRef } from 'react';
import dynamic from 'next/dynamic';
import CommunitySelector from './CommunitySelector';
import ReporterInput from './ReporterInput';

import { useProblemOptionStore } from '@/stores/useProblemOptionStore';
import ImageUploads from './ImageUploads';
import Swal from 'sweetalert2';
import { z } from 'zod';
import Image from 'next/image';
const LocationConfirm = dynamic(() => import('./LocationConfirm'), { ssr: false });

const schema = z.object({
  community: z.string().min(1, 'กรุณาระบุ 1 ชุมชน'),
});

const ComplaintFormModal = ({ selectedLabel, onClose }) => {
  const [selectedCommunity, setSelectedCommunity] = useState('');
  const [prefix, setPrefix] = useState('นาย');
  const [fullName, setFullName] = useState('');

  const [phone, setPhone] = useState('');
  const [detail, setDetail] = useState('');
  const [imageUrls, setImageUrls] = useState([]);
  const [useCurrentLocation, setUseCurrentLocation] = useState(false);
  const [location, setLocation] = useState(null);
  const [selectedProblems, setSelectedProblems] = useState([]);
  const [validateTrigger, setValidateTrigger] = useState(false);
  const [formErrors, setFormErrors] = useState({});
  const reporterValidRef = useRef(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [lastSubmitTime, setLastSubmitTime] = useState(0);

  const { problemOptions, fetchProblemOptions } = useProblemOptionStore();

useEffect(() => {
    fetchProblemOptions();
  }, [fetchProblemOptions]);

  const handleSubmit = async (e) => {
    e.preventDefault();

    // ป้องกันการส่งซ้ำ
    if (isSubmitting) {
      return;
    }

    // ป้องกันการกดปุ่มซ้ำอย่างรวดเร็ว (ภายใน 3 วินาที)
    const now = Date.now();
    if (now - lastSubmitTime < 3000) {
      await Swal.fire({
        icon: 'warning',
        title: 'กรุณารอสักครู่',
        text: 'กรุณารอ 3 วินาทีก่อนส่งใหม่',
        confirmButtonText: 'ตกลง'
      });
      return;
    }
    setLastSubmitTime(now);

    setValidateTrigger(true);
    await new Promise((resolve) => setTimeout(resolve, 0)); // allow validation effect to run

    const result = schema.safeParse({ community: selectedCommunity });
    if (!result.success) {
      setFormErrors(result.error.flatten().fieldErrors);
      return;
    } else {
      setFormErrors({});
    }

    // ตรวจสอบข้อมูลที่จำเป็นทั้งหมด
    const validationErrors = [];
    
    if (!reporterValidRef.current) {
      validationErrors.push('กรุณากรอกข้อมูลผู้แจ้งให้ถูกต้อง');
    }

    if (!location) {
      validationErrors.push('กรุณาเลือกตำแหน่ง');
    }

    if (imageUrls.length === 0) {
      validationErrors.push('กรุณาอัปโหลดรูปภาพอย่างน้อย 1 รูป');
    }

    if (!fullName.trim()) {
      validationErrors.push('กรุณากรอกชื่อผู้แจ้ง');
    }

    if (selectedProblems.length === 0) {
      validationErrors.push('กรุณาเลือกรายการปัญหาอย่างน้อย 1 รายการ');
    }

    if (validationErrors.length > 0) {
      await Swal.fire({
        icon: 'warning',
        title: 'กรุณาตรวจสอบข้อมูล',
        html: validationErrors.map(error => `• ${error}`).join('<br>'),
        confirmButtonText: 'ตกลง'
      });
      return;
    }

    // ตั้งค่า isSubmitting เป็น true ก่อนส่งข้อมูล
    setIsSubmitting(true);

    // NOTE: complaintId will be generated by the backend
    const payload = {
      fullName: fullName.trim(),
      phone: phone.trim(),
      community: selectedCommunity,
      problems: selectedProblems.map(id => {
        const match = problemOptions.find(opt => opt._id === id);
        return match ? match.label : id;
      }),
      category: selectedLabel,
      images: imageUrls,
      detail: detail.trim(),
      location,
      status: 'อยู่ระหว่างดำเนินการ',
      officer: '',
      updatedAt: new Date(),
    };

    console.log("📤 Payload ส่งไป backend:", payload);

    try {
      const res = await fetch('/api/submittedreports/submit-report', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-app-id': process.env.NEXT_PUBLIC_APP_ID || 'app_a',
        },
        body: JSON.stringify(payload),
      });
      
      console.log("📡 Response status:", res.status);
      
      if (!res.ok) {
        let errorMessage = 'ส่งข้อมูลไม่สำเร็จ';
        try {
          const errorData = await res.json();
          errorMessage = errorData.error || errorMessage;
        } catch (parseError) {
          console.error("❌ Failed to parse error response:", parseError);
        }
        
        if (res.status === 409) {
          // กรณีส่งซ้ำ
          throw new Error(errorMessage);
        }
        throw new Error(errorMessage);
      }

      const data = await res.json();
      const complaintId = data.complaintId;

      console.log("✅ Successfully submitted with complaintId:", complaintId);

      // ลดเวลา delay ลงเหลือ 2 วินาที
      await new Promise((resolve) => setTimeout(resolve, 2000));
      
      await Swal.fire({
        icon: 'success',
        title: 'ส่งเรื่องสำเร็จ',
        html: `เลขที่เรื่องของคุณคือ <strong>${complaintId}</strong><br><br>ระบบจะแจ้งเตือนไปยังเจ้าหน้าที่ที่เกี่ยวข้องแล้ว`,
        confirmButtonText: 'ตกลง',
      });
      
      handleClearForm();
      onClose?.(); // Close the modal
    } catch (err) {
      console.error('❌ เกิดข้อผิดพลาด:', err);
      await Swal.fire({
        icon: 'error',
        title: 'เกิดข้อผิดพลาด',
        text: err.message || 'ไม่สามารถส่งข้อมูลได้ กรุณาลองใหม่อีกครั้ง',
        confirmButtonText: 'ตกลง',
      });
    } finally {
      // ตั้งค่า isSubmitting เป็น false เสมอ ไม่ว่าจะสำเร็จหรือไม่
      setIsSubmitting(false);
    }
  };

  const handleClearForm = () => {
    setSelectedCommunity('');
    setPrefix('นาย');
    setFullName('');

    setPhone('');
    setDetail('');
    setImageUrls([]); // Explicitly clear imageUrls
    setUseCurrentLocation(false);
    setLocation(null);
    setSelectedProblems([]);
    setValidateTrigger(false);
    setFormErrors({});
    reporterValidRef.current = true;
  };

  const handleCommunitySelect = (community) => {
    setSelectedCommunity(community);
  };

  useEffect(() => {
  import('leaflet').then(L => {
    delete L.Icon.Default.prototype._getIconUrl;
    L.Icon.Default.mergeOptions({
      iconRetinaUrl: '/leaflet/marker-icon-2x.png',
      iconUrl: '/leaflet/marker-icon.png',
      shadowUrl: '/leaflet/marker-shadow.png',
    });
  });
}, []);

  if (!selectedLabel) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/30 overflow-y-auto flex items-center justify-center transition-all">
      <div className="bg-white rounded-lg shadow-lg p-6 w-full max-w-md max-h-[90vh] overflow-y-auto transform transition-all duration-300 opacity-0 scale-95 animate-fade-in">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-base font-semibold text-gray-800">
            ฟอร์มสำหรับ: {selectedLabel}
          </h2>
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className={`text-gray-500 hover:text-gray-800 text-sm ${isSubmitting ? 'opacity-50 cursor-not-allowed' : ''}`}
          >
            ✕
          </button>
        </div>
        <form onSubmit={handleSubmit} className="space-y-3">
          <CommunitySelector
            selected={selectedCommunity}
            onSelect={handleCommunitySelect}
            error={formErrors.community?.[0]}
          />
          <div>
            <p className="font-semibold text-sm text-gray-700">2.เลือกรายการปัญหา</p>
            <div className="flex flex-wrap gap-2 mt-2">
              {problemOptions
                .filter(option => option.category === selectedLabel)
                .map(option => (
                  <button
                    key={option._id}
                    type="button"
                    className={`inline-flex items-center gap-2 px-3 py-1 rounded-full border whitespace-nowrap ${selectedProblems.includes(option._id) ? 'bg-blue-100 text-black border-blue-300' : 'border-gray-300 text-black hover:bg-gray-100'}`}
                    onClick={() => {
                      setSelectedProblems(prev =>
                        prev.includes(option._id)
                          ? prev.filter(id => id !== option._id)
                          : [...prev, option._id]
                      );
                    }}
                  >
                    <div className="flex items-center gap-2">
                      <Image
                        src={option.iconUrl}
                        alt={option.label}
                        width={20}
                        height={20}
                        className="w-5 h-5"
                      />
                      <span>{option.label}</span>
                    </div>
                  </button>
                ))}
            </div>
          </div>
          <ImageUploads onChange={(urls) => setImageUrls(urls)} />
          <ReporterInput
            prefix={prefix}
            setPrefix={setPrefix}
            fullName={fullName}
            setFullName={setFullName}
            phone={phone}
            setPhone={setPhone}
            detail={detail}
            setDetail={setDetail}
            validateTrigger={validateTrigger}
            setValid={(v) => reporterValidRef.current = v}
          />
          <LocationConfirm
            useCurrent={useCurrentLocation}
            onToggle={setUseCurrentLocation}
            location={location}
            setLocation={setLocation}
          />
        <div className="flex mb-4 gap-2 justify-end">
          <button
            type="button"
            onClick={handleClearForm}
            disabled={isSubmitting}
            className={`btn btn-outline btn-warning ${isSubmitting ? 'opacity-50 cursor-not-allowed' : ''}`}
          >
            ล้างฟอร์ม
          </button>
          <button 
            type="submit" 
            className={`btn ${isSubmitting ? 'btn-disabled' : 'btn-info'}`} 
            disabled={isSubmitting}
          >
            {isSubmitting && <span className="loading loading-infinity loading-xs mr-2" />}
            {isSubmitting ? 'กำลังส่ง...' : 'ส่งเรื่อง'}
          </button>
        </div>
        </form>
      </div>
    </div>
  );
};

export default ComplaintFormModal;