import React, { useState, useEffect, useRef } from 'react';
import dynamic from 'next/dynamic';
import CommunitySelector from './CommunitySelector';
import ReporterInput from './ReporterInput';

import { useProblemOptionStore } from '@/stores/useProblemOptionStore';
import ImageUploads from './ImageUploads';
import Swal from 'sweetalert2';
import { z } from 'zod';
import Image from 'next/image';
import { useTranslation } from '@/hooks/useTranslation';
const LocationConfirm = dynamic(() => import('./LocationConfirm'), { ssr: false });

const ComplaintFormModal = ({ selectedLabel, onClose }) => {
  const { t, language } = useTranslation();
  
  const schema = z.object({
    community: z.string().min(1, t.form.validation.selectCommunity),
  });
  const [selectedCommunity, setSelectedCommunity] = useState('');
  const [prefix, setPrefix] = useState('นาย');
  const [fullName, setFullName] = useState('');

  const [phone, setPhone] = useState('');
  const [detail, setDetail] = useState('');
  const [imageUrls, setImageUrls] = useState([]);
  const [useCurrentLocation, setUseCurrentLocation] = useState(false);
  const [location, setLocation] = useState(null);
  const [selectedProblems, setSelectedProblems] = useState([]);
  const [validateTrigger, setValidateTrigger] = useState(false);
  const [formErrors, setFormErrors] = useState({});
  const reporterValidRef = useRef(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [lastSubmitTime, setLastSubmitTime] = useState(0);

  const { problemOptions, fetchProblemOptions } = useProblemOptionStore();

useEffect(() => {
    fetchProblemOptions();
  }, [fetchProblemOptions]);

  const handleSubmit = async (e) => {
    e.preventDefault();

    // ป้องกันการส่งซ้ำ
    if (isSubmitting) {
      return;
    }

    // ป้องกันการกดปุ่มซ้ำอย่างรวดเร็ว (ภายใน 3 วินาที)
    const now = Date.now();
    if (now - lastSubmitTime < 3000) {
      await Swal.fire({
        icon: 'warning',
        title: t.form.alert.pleaseWait,
        text: t.form.alert.waitMessage,
        confirmButtonText: t.form.alert.ok
      });
      return;
    }
    setLastSubmitTime(now);

    setValidateTrigger(true);
    await new Promise((resolve) => setTimeout(resolve, 0)); // allow validation effect to run

    const result = schema.safeParse({ community: selectedCommunity });
    if (!result.success) {
      setFormErrors(result.error.flatten().fieldErrors);
      return;
    } else {
      setFormErrors({});
    }

    // ตรวจสอบข้อมูลที่จำเป็นทั้งหมด
    const validationErrors = [];
    
    if (!reporterValidRef.current) {
      validationErrors.push(t.form.validation.reporterInvalid);
    }

    if (!location) {
      validationErrors.push(t.form.validation.selectLocation);
    }

    if (imageUrls.length === 0) {
      validationErrors.push(t.form.validation.uploadImage);
    }

    if (!fullName.trim()) {
      validationErrors.push(t.form.validation.enterReporterName);
    }

    if (selectedProblems.length === 0) {
      validationErrors.push(t.form.validation.selectProblem);
    }

    if (validationErrors.length > 0) {
      await Swal.fire({
        icon: 'warning',
        title: t.form.alert.checkData,
        html: validationErrors.map(error => `• ${error}`).join('<br>'),
        confirmButtonText: t.form.alert.ok
      });
      return;
    }

    // ตั้งค่า isSubmitting เป็น true ก่อนส่งข้อมูล
    setIsSubmitting(true);

    // NOTE: complaintId will be generated by the backend
    const payload = {
      fullName: fullName.trim(),
      phone: phone.trim(),
      community: selectedCommunity,
      problems: selectedProblems.map(id => {
        const match = problemOptions.find(opt => opt._id === id);
        return match ? match.label : id;
      }),
      category: selectedLabel,
      images: imageUrls,
      detail: detail.trim(),
      location,
      status: 'อยู่ระหว่างดำเนินการ',
      officer: '',
      updatedAt: new Date(),
    };

    console.log("📤 Payload ส่งไป backend:", payload);

    try {
      const res = await fetch('/api/submittedreports/submit-report', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-app-id': process.env.NEXT_PUBLIC_APP_ID || 'app_a',
        },
        body: JSON.stringify(payload),
      });
      
      console.log("📡 Response status:", res.status);
      
      if (!res.ok) {
        let errorMessage = 'ส่งข้อมูลไม่สำเร็จ';
        try {
          const errorData = await res.json();
          errorMessage = errorData.error || errorMessage;
        } catch (parseError) {
          console.error("❌ Failed to parse error response:", parseError);
        }
        
        if (res.status === 409) {
          // กรณีส่งซ้ำ
          throw new Error(errorMessage);
        }
        throw new Error(errorMessage);
      }

      const data = await res.json();
      const complaintId = data.complaintId;

      console.log("✅ Successfully submitted with complaintId:", complaintId);

      // ลดเวลา delay ลงเหลือ 2 วินาที
      await new Promise((resolve) => setTimeout(resolve, 2000));
      
      await Swal.fire({
        icon: 'success',
        title: t.form.alert.success,
        html: `${t.form.alert.successMessage} <strong>${complaintId}</strong><br><br>${t.form.alert.notifyOfficer}`,
        confirmButtonText: t.form.alert.ok,
      });
      
      handleClearForm();
      onClose?.(); // Close the modal
    } catch (err) {
      console.error('❌ เกิดข้อผิดพลาด:', err);
      await Swal.fire({
        icon: 'error',
        title: t.form.alert.error,
        text: err.message || t.form.alert.errorMessage,
        confirmButtonText: t.form.alert.ok,
      });
    } finally {
      // ตั้งค่า isSubmitting เป็น false เสมอ ไม่ว่าจะสำเร็จหรือไม่
      setIsSubmitting(false);
    }
  };

  const handleClearForm = () => {
    setSelectedCommunity('');
    setPrefix('นาย');
    setFullName('');

    setPhone('');
    setDetail('');
    setImageUrls([]); // Explicitly clear imageUrls
    setUseCurrentLocation(false);
    setLocation(null);
    setSelectedProblems([]);
    setValidateTrigger(false);
    setFormErrors({});
    reporterValidRef.current = true;
  };

  const handleCommunitySelect = (community) => {
    setSelectedCommunity(community);
  };

  useEffect(() => {
  import('leaflet').then(L => {
    delete L.Icon.Default.prototype._getIconUrl;
    L.Icon.Default.mergeOptions({
      iconRetinaUrl: '/leaflet/marker-icon-2x.png',
      iconUrl: '/leaflet/marker-icon.png',
      shadowUrl: '/leaflet/marker-shadow.png',
    });
  });
}, []);

  if (!selectedLabel) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/30 overflow-y-auto flex items-center justify-center transition-all">
      <div className="bg-white rounded-lg shadow-lg p-6 w-full max-w-md max-h-[90vh] overflow-y-auto transform transition-all duration-300 opacity-0 scale-95 animate-fade-in">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-base font-semibold text-gray-800">
            {t.form.formFor}: {t.categoryMap?.[selectedLabel] || selectedLabel}
          </h2>
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className={`text-gray-500 hover:text-gray-800 text-sm ${isSubmitting ? 'opacity-50 cursor-not-allowed' : ''}`}
          >
            ✕
          </button>
        </div>
        <form onSubmit={handleSubmit} className="space-y-3">
          <CommunitySelector
            selected={selectedCommunity}
            onSelect={handleCommunitySelect}
            error={formErrors.community?.[0]}
          />
          <div>
            <p className="font-semibold text-sm text-gray-700">{t.form.selectProblem}</p>
            <div className="flex flex-wrap gap-2 mt-2">
              {problemOptions
                .filter(option => option.category === selectedLabel)
                .map(option => {
                  const displayLabel = language === 'en' && option.labelEn ? option.labelEn : option.label;
                  return (
                    <button
                      key={option._id}
                      type="button"
                      className={`inline-flex items-center gap-2 px-3 py-1 rounded-full border whitespace-nowrap ${selectedProblems.includes(option._id) ? 'bg-blue-100 text-black border-blue-300' : 'border-gray-300 text-black hover:bg-gray-100'}`}
                      onClick={() => {
                        setSelectedProblems(prev =>
                          prev.includes(option._id)
                            ? prev.filter(id => id !== option._id)
                            : [...prev, option._id]
                        );
                      }}
                    >
                      <div className="flex items-center gap-2">
                        <Image
                          src={option.iconUrl}
                          alt={displayLabel}
                          width={20}
                          height={20}
                          className="w-5 h-5"
                        />
                        <span>{displayLabel}</span>
                      </div>
                    </button>
                  );
                })}
            </div>
          </div>
          <ImageUploads onChange={(urls) => setImageUrls(urls)} />
          <ReporterInput
            prefix={prefix}
            setPrefix={setPrefix}
            fullName={fullName}
            setFullName={setFullName}
            phone={phone}
            setPhone={setPhone}
            detail={detail}
            setDetail={setDetail}
            validateTrigger={validateTrigger}
            setValid={(v) => reporterValidRef.current = v}
          />
          <LocationConfirm
            useCurrent={useCurrentLocation}
            onToggle={setUseCurrentLocation}
            location={location}
            setLocation={setLocation}
          />
        <div className="flex mb-4 gap-2 justify-end">
          <button
            type="button"
            onClick={handleClearForm}
            disabled={isSubmitting}
            className={`btn btn-outline btn-warning ${isSubmitting ? 'opacity-50 cursor-not-allowed' : ''}`}
          >
            {t.form.clearForm}
          </button>
          <button 
            type="submit" 
            className={`btn ${isSubmitting ? 'btn-disabled' : 'btn-info'}`} 
            disabled={isSubmitting}
          >
            {isSubmitting && <span className="loading loading-infinity loading-xs mr-2" />}
            {isSubmitting ? t.form.submitting : t.form.submit}
          </button>
        </div>
        </form>
      </div>
    </div>
  );
};

export default ComplaintFormModal;